// Generated by Apple Swift version 5.1.3 effective-4.2 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CVCalendar",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSCoder;

SWIFT_CLASS("_TtC10CVCalendar15CVAuxiliaryView")
@interface CVAuxiliaryView : UIView
- (void)didMoveToSuperview;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end





@class NSBundle;

SWIFT_CLASS("_TtC10CVCalendar31CVCalendarContentViewController")
@interface CVCalendarContentViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface CVCalendarContentViewController (SWIFT_EXTENSION(CVCalendar)) <UIScrollViewDelegate>
@end




@interface CVCalendarContentViewController (SWIFT_EXTENSION(CVCalendar))
- (void)updateFrames:(CGRect)frame;
@end











@class CVCalendarDayView;

@interface CVCalendarContentViewController (SWIFT_EXTENSION(CVCalendar))
- (void)performedDayViewSelection:(CVCalendarDayView * _Nonnull)dayView;
- (void)togglePresentedDate:(NSDate * _Nonnull)date;
- (void)presentNextView:(UIView * _Nullable)view;
- (void)presentPreviousView:(UIView * _Nullable)view;
- (void)updateDayViewsWithShouldShow:(BOOL)shouldShow;
@end


SWIFT_CLASS("_TtC10CVCalendar17CVCalendarDayView")
@interface CVCalendarDayView : UIView
@property (nonatomic) CGRect frame;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end














SWIFT_CLASS("_TtC10CVCalendar18CVCalendarMenuView")
@interface CVCalendarMenuView : UIView
@property (nonatomic, weak) IBOutlet id _Nullable menuViewDelegate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

enum CVCalendarWeekday : NSInteger;
@class UIColor;
@class UIFont;
enum CVWeekdaySymbolType : NSInteger;

SWIFT_PROTOCOL("_TtP10CVCalendar26CVCalendarMenuViewDelegate_")
@protocol CVCalendarMenuViewDelegate
@optional
- (enum CVCalendarWeekday)firstWeekday SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayOfWeekTextColorBy:(enum CVCalendarWeekday)weekday SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayOfWeekBackGroundColorBy:(enum CVCalendarWeekday)weekday SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayOfWeekTextColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayOfWeekBackGroundColor SWIFT_WARN_UNUSED_RESULT;
- (BOOL)dayOfWeekTextUppercase SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)dayOfWeekFont SWIFT_WARN_UNUSED_RESULT;
- (enum CVWeekdaySymbolType)weekdaySymbolType SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC10CVCalendar36CVCalendarMonthContentViewController")
@interface CVCalendarMonthContentViewController : CVCalendarContentViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)updateFrames:(CGRect)rect;
- (void)performedDayViewSelection:(CVCalendarDayView * _Nonnull)dayView;
- (void)presentPreviousView:(UIView * _Nullable)view;
- (void)presentNextView:(UIView * _Nullable)view;
- (void)updateDayViewsWithShouldShow:(BOOL)shouldShow;
- (void)togglePresentedDate:(NSDate * _Nonnull)date;
@end



@class UIScrollView;

@interface CVCalendarMonthContentViewController (SWIFT_EXTENSION(CVCalendar))
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
@end




SWIFT_CLASS("_TtC10CVCalendar19CVCalendarMonthView")
@interface CVCalendarMonthView : UIView
@property (nonatomic) CGRect frame;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end









@class UILongPressGestureRecognizer;
@class UITapGestureRecognizer;

@interface CVCalendarMonthView (SWIFT_EXTENSION(CVCalendar))
- (void)didPressInteractiveView:(UILongPressGestureRecognizer * _Nonnull)recognizer;
- (void)didTouchInteractiveView:(UITapGestureRecognizer * _Nonnull)recognizer;
@end


SWIFT_CLASS("_TtC10CVCalendar14CVCalendarView")
@interface CVCalendarView : UIView
@property (nonatomic, weak) IBOutlet id _Nullable calendarDelegate;
@property (nonatomic, weak) IBOutlet id _Nullable calendarAppearanceDelegate;
@property (nonatomic, weak) IBOutlet id _Nullable animatorDelegate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end










SWIFT_PROTOCOL("_TtP10CVCalendar30CVCalendarViewAnimatorDelegate_")
@protocol CVCalendarViewAnimatorDelegate
- (void (^ _Nonnull)(CVCalendarDayView * _Nonnull, void (^ _Nonnull)(BOOL)))selectionAnimation SWIFT_WARN_UNUSED_RESULT;
- (void (^ _Nonnull)(CVCalendarDayView * _Nonnull, void (^ _Nonnull)(BOOL)))deselectionAnimation SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC10CVCalendar24CVCalendarViewAppearance")
@interface CVCalendarViewAppearance : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum CVStatus : NSInteger;
enum CVPresent : NSInteger;

SWIFT_PROTOCOL("_TtP10CVCalendar32CVCalendarViewAppearanceDelegate_")
@protocol CVCalendarViewAppearanceDelegate
@optional
- (CGFloat)spaceBetweenWeekViews SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)spaceBetweenDayViews SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)dayLabelFontBy:(enum CVCalendarWeekday)weekDay status:(enum CVStatus)status present:(enum CVPresent)present SWIFT_WARN_UNUSED_RESULT;
- (BOOL)dayLabelPresentWeekdayInitallyBold SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)dayLabelWeekdayFont SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)dayLabelPresentWeekdayFont SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)dayLabelPresentWeekdayBoldFont SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)dayLabelPresentWeekdayHighlightedFont SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)dayLabelPresentWeekdaySelectedFont SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)dayLabelWeekdayHighlightedFont SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)dayLabelWeekdaySelectedFont SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)dayLabelColorBy:(enum CVCalendarWeekday)weekDay status:(enum CVStatus)status present:(enum CVPresent)present SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelWeekdayDisabledColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelWeekdayInTextColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelWeekdayOutTextColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelWeekdayHighlightedTextColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelWeekdaySelectedTextColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelPresentWeekdayTextColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelPresentWeekdayHighlightedTextColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelPresentWeekdaySelectedTextColor SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelSizeBy:(enum CVCalendarWeekday)weekDay status:(enum CVStatus)status present:(enum CVPresent)present SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelWeekdayTextSize SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelWeekdayHighlightedTextSize SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelWeekdaySelectedTextSize SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelPresentWeekdayTextSize SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelPresentWeekdayHighlightedTextSize SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelPresentWeekdaySelectedTextSize SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)dayLabelBackgroundColorBy:(enum CVCalendarWeekday)weekDay status:(enum CVStatus)status present:(enum CVPresent)present SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelWeekdayHighlightedBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelWeekdayHighlightedBackgroundAlpha SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelPresentWeekdayHighlightedBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelPresentWeekdayHighlightedBackgroundAlpha SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelWeekdaySelectedBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelWeekdaySelectedBackgroundAlpha SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelPresentWeekdaySelectedBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelPresentWeekdaySelectedBackgroundAlpha SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dotMarkerColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)topMarkerColor SWIFT_WARN_UNUSED_RESULT;
@end

enum CVCalendarViewPresentationMode : NSInteger;
@class CVDate;
@class UIBezierPath;

SWIFT_PROTOCOL("_TtP10CVCalendar22CVCalendarViewDelegate_")
@protocol CVCalendarViewDelegate
- (enum CVCalendarViewPresentationMode)presentationMode SWIFT_WARN_UNUSED_RESULT;
- (enum CVCalendarWeekday)firstWeekday SWIFT_WARN_UNUSED_RESULT;
@optional
- (BOOL)shouldAnimateResizing SWIFT_WARN_UNUSED_RESULT;
- (double)toggleDateAnimationDuration SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldScrollOnOutDayViewSelection SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldAutoSelectDayOnWeekChange SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldAutoSelectDayOnMonthChange SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldShowWeekdaysOut SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldSelectDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (void)didSelectDayView:(CVCalendarDayView * _Nonnull)dayView animationDidFinish:(BOOL)animationDidFinish;
- (void)presentedDateUpdated:(CVDate * _Nonnull)date;
- (BOOL)topMarkerWithShouldDisplayOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (BOOL)dotMarkerWithShouldMoveOnHighlightingOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (BOOL)dotMarkerWithShouldShowOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (NSArray<UIColor *> * _Nonnull)dotMarkerWithColorOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dotMarkerWithMoveOffsetOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dotMarkerWithSizeOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (UIBezierPath * _Nonnull (^ _Nonnull)(CGRect))selectionViewPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldShowCustomSingleSelection SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)preliminaryViewWithViewOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (BOOL)preliminaryViewWithShouldDisplayOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)supplementaryViewWithViewOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (BOOL)supplementaryViewWithShouldDisplayOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (void)didShowNextMonthView:(NSDate * _Nonnull)date;
- (void)didShowPreviousMonthView:(NSDate * _Nonnull)date;
- (NSCalendar * _Nullable)calendar SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldSelectRange SWIFT_WARN_UNUSED_RESULT;
- (void)didSelectRangeFrom:(CVCalendarDayView * _Nonnull)startDayView to:(CVCalendarDayView * _Nonnull)endDayView;
- (NSDate * _Nonnull)disableScrollingBeforeDate SWIFT_WARN_UNUSED_RESULT;
- (NSDate * _Nonnull)disableScrollingBeyondDate SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)maxSelectableRange SWIFT_WARN_UNUSED_RESULT;
- (NSDate * _Nonnull)earliestSelectableDate SWIFT_WARN_UNUSED_RESULT;
- (NSDate * _Nonnull)latestSelectableDate SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, CVCalendarViewPresentationMode, closed) {
  CVCalendarViewPresentationModeMonthView = 0,
  CVCalendarViewPresentationModeWeekView = 1,
};


SWIFT_CLASS("_TtC10CVCalendar35CVCalendarWeekContentViewController")
@interface CVCalendarWeekContentViewController : CVCalendarContentViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)updateFrames:(CGRect)rect;
- (void)performedDayViewSelection:(CVCalendarDayView * _Nonnull)dayView;
- (void)presentPreviousView:(UIView * _Nullable)view;
- (void)presentNextView:(UIView * _Nullable)view;
- (void)updateDayViewsWithShouldShow:(BOOL)shouldShow;
- (void)togglePresentedDate:(NSDate * _Nonnull)date;
@end








@interface CVCalendarWeekContentViewController (SWIFT_EXTENSION(CVCalendar))
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
@end


SWIFT_CLASS("_TtC10CVCalendar18CVCalendarWeekView")
@interface CVCalendarWeekView : UIView
@property (nonatomic) CGRect frame;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end






@interface CVCalendarWeekView (SWIFT_EXTENSION(CVCalendar))
- (void)didPressInteractiveView:(UILongPressGestureRecognizer * _Nonnull)recognizer;
- (void)didTouchInteractiveView:(UITapGestureRecognizer * _Nonnull)recognizer;
@end

typedef SWIFT_ENUM(NSInteger, CVCalendarWeekday, closed) {
  CVCalendarWeekdaySunday = 1,
  CVCalendarWeekdayMonday = 2,
  CVCalendarWeekdayTuesday = 3,
  CVCalendarWeekdayWednesday = 4,
  CVCalendarWeekdayThursday = 5,
  CVCalendarWeekdayFriday = 6,
  CVCalendarWeekdaySaturday = 7,
};


SWIFT_CLASS("_TtC10CVCalendar6CVDate")
@interface CVDate : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end







typedef SWIFT_ENUM(NSInteger, CVPresent, closed) {
  CVPresentPresent = 0,
  CVPresentNot = 1,
};

typedef SWIFT_ENUM(NSInteger, CVStatus, closed) {
  CVStatusIn = 0,
  CVStatusOut = 1,
  CVStatusDisabled = 2,
  CVStatusSelected = 3,
  CVStatusHighlighted = 4,
};

typedef SWIFT_ENUM(NSInteger, CVWeekdaySymbolType, closed) {
  CVWeekdaySymbolTypeNormal = 0,
  CVWeekdaySymbolTypeShort = 1,
  CVWeekdaySymbolTypeVeryShort = 2,
};





#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
