# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ToDoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToDoApp
  pod 'CVCalendar', '~> 1.6.2'
  pod 'FSCalendar'

  target 'ToDoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ToDoAppUITests' do
    # Pods for testing
  end

end
