//
//  DataModel.swift
//  OzdemirZ_TableViewApp
//
//  Created by Zubeyir Ozdemir on 03/07/20.
//  Copyright © 2020 Zubeyir Ozdemir. All rights reserved.
//

import Foundation

struct Restaurant {
    var name: String
    var about: String
    var cuisines: String
    var priceRange: String
    var specialDiets: String
    var meals: String
    var features: String
}

class DataModel {
    var restaurants = [Restaurant]()
    
    // this property is used to access current instance of this class
    static let shared: DataModel = {
        let instance = DataModel()
        return instance
    }()
    
    
    // this method calls when object of this class created
    init() {
        restaurants = [
            Restaurant(name: "Oriole", about: "Oriole is a restaurant in a quiet stretch of Chicago's West Loop neighborhood, offering an extended tasting menu presented by Executive Chef & Owner Noah Sandoval and Pastry Chef & Partner Genie Kwon. Never bending to industry trends, the dishes and service at Oriole will give guests a thought-provoking and interactive experience, where the diner is the true focus of the meal.", cuisines: "American", priceRange: "US$ 175 - US$ 176", specialDiets: "Gluten Free Options", meals: "Dinner", features: "Reservations, Seating, Wheelchair Accessible, Serves Alcohol, Full Bar, Accepts Credit Cards, Table Service"),
            Restaurant(name: "The Polo Inn Bridgeport U.S.A.", about: "Located 10-15 minutes SW of Chicago's downtown, chef-owner-innkeeper Dave Samber and his Polo Staff continue to bring you \"Something different... something wonderful!\" through their excellence in hospitality since 1985. Whether it's Dinner on FRI or SAT, Lunch MON-FRI, or SAT/SUN's Brunch, you can count on delicious tastes and generous portions from the kitchen, and personal service from Adam and Rob in the 1914 candy store dining room. Host an event in our attached elegant Old Eagle Room (a renovated 104-year-old picture show) for up to 100 guests, or let us cater at your location; even stay for a weekend in the handsome bed and breakfast upstairs. Reservations are recommended; parking is complimentary. Now in our 34th year, we offer our years of experience and commitment to bringing you back for more...nothing pretentious, priced right, totally Chicago!!", cuisines: "American, Grill, Healthy", priceRange: "US$ 6 - US$ 55", specialDiets: "Vegetarian Friendly, Vegan Options, Gluten Free Options", meals: "Lunch, Dinner, Brunch, Drinks", features: "Parking Available, Wheelchair Accessible, Full Bar, Takeout, Reservations, Private Dining, Seating, Street Parking, Free Off-Street Parking, Highchairs Available, Serves Alcohol, Accepts American Express, Accepts Mastercard, Accepts Visa, Free Wifi, Accepts Discover, Accepts Credit Cards, Table Service"),
            Restaurant(name: "Joe's Seafood, Prime Steak & Stone Crab", about: "Joe's Seafood, Prime Steak & Stone Crab is the culmination of a partnership between Lettuce Entertain You and Joe's Stone Crab, the legendary seafood restaurant of Miami Beach. Joe's features an extensive selection of seafood, flown in fresh daily, to complement the world's finest Florida Stone Crab claws. Joe's features the signature 16 oz. Bone-In Filet Mignon and 22 oz. New York Strip Steak. Matched with Joe's famous side dishes, dinner only gets better when capped with a slice of key lime pie.Defined by a standard of hospitality born a century ago, Joe’s offers a dining experience that is timeless. Tuxedo-clad service provides a sense of tradition, while delivering the warmth and caring service that has defined Joe’s since 1913.", cuisines: "Steakhouse, American, Seafood", priceRange: "US$ 41 - US$ 80", specialDiets: "Vegetarian Friendly, Vegan Options, Gluten Free Options", meals: "Lunch, Dinner", features: "Seating, Parking Available, Street Parking, Valet Parking, Television, Highchairs Available, Wheelchair Accessible, Serves Alcohol, Full Bar, Accepts American Express, Accepts Mastercard, Accepts Visa, Accepts Discover, Takeout, Reservations, Private Dining, Free Wifi, Accepts Credit Cards, Table Service"),
            Restaurant(name: "The Chicago Diner", about: "April 2, 1983. In a city known for meat packing & hog butchering, a brave pair of optimistic vegetarians opened a ground breaking meat free eatery called The Chicago Diner. Since then, co-owners Mickey Hornick & Jo Kaucher, have built a reputation for wowing customers with unique and innovative dishes, changing minds about “The Way a Diner Should Be”.", cuisines: "American, Diner", priceRange: "US$ 10 - US$ 15", specialDiets: "Vegetarian Friendly, Vegan Options, Gluten Free Options", meals: "Breakfast, Lunch, Dinner, Brunch", features: "Takeout, Seating, Highchairs Available, Wheelchair Accessible, Serves Alcohol, Table Service, Wine and Beer"),
            Restaurant(name: "Girl & The Goat", about: "Girl & the Goat has been serving fun foods, craft beers, and making wine in a rustic and kick-butt environment since summer 2010. The restaurant opens at 4:30 every day, and stays open until 11pm on weeknights and until midnight on Fridays and Saturdays (until those last late night eaters scrape their fork across the plate for the last time, or finish licking their plates until they're shiny and clean). The Goat's menu is divided into three categories: Vegetable, Fish, and of course Meat--while vegetable, fish, or meat are respectively the main stars of their categories, there are crossovers in each area so you'll get a little bit of everything. Bread is baked daily, and there are always new creations on the menu. Girl & the Goat sits in the West Loop smack dab in the Randolph Restaurant Corridor, but the location is still gritty enough to appeal to the chef’s integrity. The Goat has a variety of seating choices, including a comfortable lounge, bar seats, standard table seating, and four seats close enough to the kitchen line that you might be asked to help.Girl & the Goat blended their own wine, and it's tasty. There are beers on tap from Three Floyd’s and a couple others. If you're lucky, you might come across the elusive collaboration beers that Stephanie personally crafted with a couple of beer buddy cohorts. In addition to tap beers, there's also a bunch of bottles to choose from. Girl & the Goat is open 7 days a week, because The Goat is a tireless beast, and besides, who needs rest anyway? Girl & the Goat accepts reservations but always welcomes walk-ins, nomads, adventurers, and those of you who don’t like to plan.", cuisines: "American", priceRange: "US$ 15 - US$ 30", specialDiets: "Vegetarian Friendly, Vegan Options, Gluten Free Options", meals: "Dinner, After-hours", features: "Reservations, Seating, Valet Parking, Wheelchair Accessible, Serves Alcohol, Full Bar, Accepts Credit Cards, Table Service"),
            Restaurant(name: "Lula Cafe", about: "Since 1999, Lula has served locally sourced creative cuisine in a relaxed cafe setting from Chef Jason Hammel.", cuisines: "American, Cafe", priceRange: "-", specialDiets: "Vegetarian Friendly, Vegan Options, Gluten Free Options", meals: "Breakfast, Lunch, Dinner, Brunch, After-hours, Drinks", features: "Reservations, Outdoor Seating, Seating, Highchairs Available, Wheelchair Accessible, Serves Alcohol, Full Bar, Accepts Credit Cards, Table Service"),
            Restaurant(name: "The Capital Grille", about: "Make it a day to remember. From birthdays and anniversaries to professional milestones, we aim to make every gathering special at The Capital Grille. Open seven days a week, The Capital Grille is best known for its expertly prepared steaks, which are dry-aged in house for 18 to 24 days and then hand-cut by our restaurant's on-premise butcher. The Capital Grille's wine list features more than 350 selections, and its floor-to-ceiling wine kiosk regularly houses 3,500 - 5,000 bottles. Reservations are recommended but not required. For more information, please visit our website. See you soon.", cuisines: "American, Steakhouse", priceRange: "US$ 40 - US$ 80", specialDiets: "Vegetarian Friendly, Gluten Free Options", meals: "Lunch, Dinner, Drinks", features: "Seating, Validated Parking, Valet Parking, Highchairs Available, Wheelchair Accessible, Serves Alcohol, Full Bar, Free Wifi, Accepts Credit Cards, Table Service, Wine and Beer"),
            Restaurant(name: "RPM Italian", about: "RPM Italian presents cuisine that is modern in approach and Italian in spirit, with dishes intended to be shared. Chef partner Doug Psaltis has created a menu which features a variety of cold and hot antipasti, more than a dozen freshly prepared in-house pastas, and a selection of salads, prime steaks, chops and slow-roasted meats. The restaurant also has an open bar area where guests can order a signature cocktail, or enjoy a glass of wine from their extensive list. Sophisticated and chic, yet unpretentious, RPM Italian is perfect for a great meal or late night out.", cuisines: "Italian", priceRange: "US$ 30 - US$ 40", specialDiets: "Vegetarian Friendly, Vegan Options, Gluten Free Options", meals: "Dinner, After-hours", features: "Delivery, Takeout, Parking Available, Highchairs Available, Reservations, Private Dining, Seating, Street Parking, Valet Parking, Free Off-Street Parking, Wheelchair Accessible, Serves Alcohol, Full Bar, Accepts American Express, Accepts Mastercard, Accepts Visa, Free Wifi, Accepts Discover, Accepts Credit Cards, Table Service"),
            Restaurant(name: "Bavette's Bar and Boeuf", about: "A stylish departure from a traditional steakhouse, Bavette's embraces French flair without the formality, blending fine dining with unabashed fun. Guests can indulge in seafood towers, richly flavorful ribeyes, classic side dishes and house made desserts, as well as classic cocktails and a well-curated international wine list.", cuisines: "American, Steakhouse", priceRange: "US$ 31 - US$ 50", specialDiets: "Vegetarian Friendly, Gluten Free Options", meals: "Dinner, After-hours", features: "Reservations, Private Dining, Seating, Valet Parking, Wheelchair Accessible, Serves Alcohol, Full Bar, Accepts Credit Cards, Table Service, Jazz Bar, BYOB"),
            Restaurant(name: "Shaw's Crab House", about: "Big and Bustling, Shaw's Crab House stands as a monument to fish and seafood. Besides the usual popular dishes, Shaw's management team is passionate about presenting treats such as Pacific salmon, fresh king crab, and smelt during their short seasons. Reservations made through Open Table will be for Shaw's Main Dining Room. If you would like to dine in the Oyster Bar, all seating is on a first come first serve basis.", cuisines: "American, Seafood, Sushi, Soups", priceRange: "US$ 31 - US$ 40", specialDiets: "Vegetarian Friendly, Gluten Free Options", meals: "Lunch, Dinner, Brunch, After-hours", features: "Takeout, Reservations, Private Dining, Seating, Valet Parking, Television, Highchairs Available, Wheelchair Accessible, Serves Alcohol, Full Bar, Free Wifi, Accepts Credit Cards, Table Service, Live Music, Jazz Bar"),
            Restaurant(name: "Steak 48", about: "Not just another steakhouse, Steak 48 - Chicago is a warm contemporary steakhouse featuring prime steaks, a raw bar and extensive fresh seafood selection, unique appetizers including ahi poke and deviled eggs with crisps shrimp and side dishes including a double baked truffle potato, asparagus fries and corn crème brûlée, classic cocktails and an extensive award winning wine list.", cuisines: "American, Steakhouse", priceRange: "US$ 31 - US$ 50", specialDiets: "Gluten Free Options", meals: "Lunch, Dinner", features: "Reservations, Seating, Parking Available, Street Parking, Valet Parking, Free Off-Street Parking, Wheelchair Accessible, Serves Alcohol, Full Bar, Accepts American Express, Accepts Mastercard, Accepts Visa, Accepts Discover, Table Service"),
            Restaurant(name: "Trattoria No. 10", about: "Classic Italian dishes with a contemporary flair have made Trattoria No.10 a Chicago favorite since 1989. Specialties on the seasonal menu include unique, homemade ravioli, rustic pastas, freshly prepared risotto, sustainable fish selections and grass fed veal scaloppini. The subdued elegance of the interior, with arched walkways, murals and original art provides an intimate atmosphere that is perfect for pre-theater dining, romantic dinners or private parties.", cuisines: "Italian, Contemporary", priceRange: "US$ 21 - US$ 40", specialDiets: "Vegetarian Friendly, Vegan Options, Gluten Free Options", meals: "Dinner, Drinks", features: "Reservations, Private Dining, Seating, Valet Parking, Highchairs Available, Wheelchair Accessible, Serves Alcohol, Full Bar, Accepts Credit Cards, Table Service")
        ]
    }
}
